### ISSUE TITLE
Handle situation when `recv` returns 0.

### ISSUE THREAD

**Issue by VyacheslavHashov** [lpeterse/haskell-socket#42]
According to the `man recv`:
```
The return value will be 0 when the peer has performed an orderly shutdown.
```
But now `receive` returns empty bytestring infinitely and the socket stays in CLOSE_WAIT state.
One of the possible actions here is to close the socket's descriptor and to throw `eBadFileDesciptor`.

**Comment by lpeterse** [comment]
Hi and sorry for the delay.

I looked into this. This is IMHO the expected behavior. Returning an empty bytestring is the closest equivalent to returning 0 I could think of. When designing the API I also considered returning `Maybe ByteString`, but then decided that would already be less simple. In both cases the return value must be inspected for emptiness after each `recv` and the application must deal with it (probably closing the socket).

The `network` library behaves the same:

> For TCP sockets, a zero length return value means the peer has closed its half side of the connection.

I think that throwing `eBadFileDescriptor` would be wrong as the socket itself (the data structure in kernel space) is still present until closed. It's just in `CLOSE_WAIT` state. As a library user, I'd also find it quite surprising if any other operation than `close` would close and free my socket.

I'll leave the ticket open in case there's more need for discussion on this.

**Comment by VyacheslavHashov** [comment]
Maybe write in haddocks for `receive` about this behavior? It was not obvious to me.

**Comment by lpeterse** [comment]
Done.
